export type Category = 'valor' | 'bateo' | 'pitcheo' | 'statcast' | 'campo' | 'contexto'

export interface Entry {
  id: string
  label: string
  full: string
  category: Category
  /** una frase para la tarjeta que aparece al pasar el mouse */
  short: string
  what: string
  /** escala de referencia: [rango, significado] */
  scale?: [string, string][]
  scaleNote?: string
  use: string
  worth: string
  example?: string
  related?: string[]
  /** textos que se enlazan automáticamente en los párrafos (el orden importa: los largos primero) */
  aliases: string[]
}

export const CATEGORIES: Record<Category, string> = {
  valor: 'Valor total',
  bateo: 'Bateo',
  pitcheo: 'Pitcheo',
  statcast: 'Contacto y Statcast',
  campo: 'Defensa y corrido',
  contexto: 'Impacto en el juego',
}

const E: Entry[] = [
  {
    id: 'war', label: 'WAR', full: 'Wins Above Replacement (victorias sobre un reemplazo)', category: 'valor',
    short: 'Cuántas victorias aporta un jugador a su equipo en una temporada, comparado con un suplente de nivel mínimo.',
    what: 'Junta en un solo número lo que el jugador hace bateando, corriendo las bases y defendiendo (o lanzando), ajustado por la posición que juega. Un "jugador de reemplazo" es un suplente que cualquier equipo consigue casi gratis, y vale 0. Un jugador con 6.0 de WAR significa que su equipo ganó unos 6 juegos más que si hubiera usado a ese suplente.',
    scale: [['0 a 1', 'suplente'], ['1 a 2', 'jugador de rol'], ['2 a 3', 'titular sólido'], ['3 a 5', 'muy buen jugador (nivel All-Star desde 4)'], ['5 a 8', 'súper estrella'], ['8 o más', 'nivel MVP']],
    scaleNote: 'Es una escala aproximada que usan FanGraphs y otros sitios. Una temporada completa suele ser de 162 juegos.',
    use: 'Compara jugadores de posiciones distintas con la misma vara: un cátcher con un jardinero, un bateador con un lanzador. Es la base de casi todos los argumentos modernos de MVP.',
    worth: 'Es la mejor síntesis de valor total que existe, pero no es exacta. Hay dos versiones principales (fWAR de FanGraphs y bWAR de Baseball Reference) que pueden diferir más de una victoria, sobre todo en defensa y en lanzadores. Una diferencia de menos de 1 WAR entre dos jugadores no prueba que uno sea mejor. En los últimos 10 años fue lo que más explicó el voto del MVP.',
    example: 'En 2026, Pete Crow-Armstrong terminó con 10.6 fWAR. El segundo bateador de la Nacional tuvo 6.4.',
    related: ['fwar', 'bwar'], aliases: ['WAR'],
  },
  {
    id: 'fwar', label: 'fWAR', full: 'WAR de FanGraphs', category: 'valor',
    short: 'La versión de WAR de FanGraphs. A los lanzadores los mide por lo que controlan: ponches, boletos y jonrones.',
    what: 'Es el WAR que calcula FanGraphs. Para bateadores usa su producción ofensiva, su defensa y su corrido de bases. Para lanzadores usa el FIP en lugar de las carreras que realmente permitieron, así no depende de la defensa que tuvieron detrás ni de la suerte.',
    scale: [['0 a 1', 'suplente'], ['2 a 3', 'titular sólido'], ['4 a 5', 'All-Star'], ['6 a 8', 'súper estrella'], ['8 o más', 'nivel MVP']],
    use: 'MLB.com cita tanto este como el bWAR en sus encuestas de MVP. FanGraphs lo actualiza todos los días.',
    worth: 'Es más estable con los lanzadores porque ignora la defensa de su equipo. A cambio, puede quedarse corto con quien permite poco contacto fuerte, algo que el FIP no ve. Siempre conviene mirarlo junto con el bWAR.',
    example: 'Kevin McGonigle tuvo 5.4 de fWAR en 2026, bastante menos que sus 7.1 de bWAR.',
    related: ['war', 'bwar', 'fip'], aliases: ['fWAR'],
  },
  {
    id: 'bwar', label: 'bWAR', full: 'WAR de Baseball Reference', category: 'valor',
    short: 'La versión de WAR de Baseball Reference. A los lanzadores los mide por las carreras que realmente permitieron.',
    what: 'Es el WAR de Baseball Reference. Para lanzadores parte de las carreras que permitieron de verdad, ajustadas por el estadio y por la defensa de su equipo. Para bateadores combina bateo, corrido, defensa y posición con métodos algo distintos a los de FanGraphs.',
    scale: [['0 a 1', 'suplente'], ['2 a 3', 'titular sólido'], ['4 a 5', 'All-Star'], ['6 a 8', 'súper estrella'], ['8 o más', 'nivel MVP']],
    use: 'Es el que se ve en las páginas de cada jugador en Baseball Reference y el que usa esa web en su historial de premios.',
    worth: 'Premia al lanzador que de verdad evitó carreras, pero depende más de la defensa y de la suerte con los batazos. Por eso a veces se separa mucho de fWAR.',
    example: 'Cristopher Sánchez tuvo 8.1 de bWAR en 2026 pero solo 6.2 de fWAR: dos formas de medir el mismo año.',
    related: ['war', 'fwar'], aliases: ['bWAR'],
  },
  {
    id: 'wrcplus', label: 'wRC+', full: 'Carreras creadas ponderadas, ajustadas (weighted Runs Created Plus)', category: 'bateo',
    short: 'Qué tan buen bateador es: 100 es el promedio de la liga y cada punto de más es 1% mejor que el promedio.',
    what: 'Mide cuánta ofensiva produce un bateador. Cada resultado (sencillo, jonrón, boleto) se pondera por lo que vale en carreras. Luego se ajusta por el estadio donde juega y por la época, y se compara con el promedio de la liga, que vale 100. Un 150 significa 50% más ofensiva que un bateador promedio.',
    scale: [['Menos de 90', 'por debajo del promedio'], ['100', 'promedio de la liga'], ['115', 'por encima del promedio'], ['140', 'muy bueno'], ['160 o más', 'élite']],
    use: 'Para saber qué tan bueno es el bate de alguien y compararlo con jugadores de otros estadios y otras épocas.',
    worth: 'Es mejor que el OPS porque pesa cada resultado por su valor real y ajusta por el estadio. Mide solo el bateo: no incluye defensa ni corrido de bases, por eso un excelente bate puede tener poco WAR.',
    example: 'Yordan Álvarez tuvo 181 de wRC+ en 2026: produjo 81% más ofensiva que un bateador promedio.',
    related: ['woba', 'ops', 'war'], aliases: ['wRC+'],
  },
  {
    id: 'woba', label: 'wOBA', full: 'Promedio ponderado de embasarse (weighted On-Base Average)', category: 'bateo',
    short: 'Un promedio de embasarse que da a cada resultado el peso real que tiene: un jonrón vale mucho más que un boleto.',
    what: 'Se lee igual que el OBP y está en una escala parecida, pero corrige un defecto: el OBP cuenta igual un boleto y un jonrón. El wOBA le da a cada resultado el valor en carreras que produce en promedio (un sencillo vale menos que un doble, un doble menos que un jonrón).',
    scale: [['.290', 'malo'], ['.320', 'promedio'], ['.340', 'sobre el promedio'], ['.370', 'muy bueno'], ['.400 o más', 'excelente']],
    use: 'Medir el valor ofensivo total de un bateador con un solo promedio fácil de leer. Es la base de wRC+.',
    worth: 'Es mucho más preciso que el AVG o el OPS para medir producción. No ajusta por estadio (para eso está el wRC+) y no incluye defensa ni corrido.',
    example: 'Yordan Álvarez tuvo .429 de wOBA en 2026.',
    related: ['xwoba', 'wrcplus', 'obp'], aliases: ['wOBA'],
  },
  {
    id: 'xwoba', label: 'xwOBA', full: 'wOBA esperado (expected wOBA)', category: 'statcast',
    short: 'Lo que debería ser el wOBA de un bateador según qué tan fuerte y con qué ángulo pegó la pelota, sin contar la suerte.',
    what: 'Statcast mide la velocidad de salida y el ángulo de cada batazo y calcula qué producen, en promedio, batazos iguales. Así premia el buen contacto aunque un jardinero lo haya atrapado, y no premia el hit con mucha suerte. Los ponches y los boletos cuentan igual que en el wOBA. Las versiones xBA y xSLG usan la misma lógica.',
    scale: [['.290', 'malo'], ['.320', 'promedio'], ['.370', 'muy bueno'], ['.400 o más', 'excelente']],
    scaleNote: 'Misma escala que el wOBA.',
    use: 'Separar al que batea bien de verdad del que tuvo suerte (o mala suerte). Si el wOBA de alguien está muy por encima de su xwOBA, es probable que baje.',
    worth: 'Predice mejor el futuro que el resultado real, pero no lo reemplaza: son los resultados reales los que ganaron juegos. Funciona mejor con muestras grandes (toda una temporada).',
    example: 'Yordan Álvarez tuvo .442 de xwOBA en 2026, incluso más alto que su wOBA real (.429).',
    related: ['woba', 'ev', 'barrel'], aliases: ['xwOBA'],
  },
  {
    id: 'xstats', label: 'xBA y xSLG', full: 'Promedio y slugging esperados', category: 'statcast',
    short: 'Lo que debería ser el promedio (xBA) y el slugging (xSLG) de un bateador según la calidad de su contacto.',
    what: 'Funcionan igual que el xwOBA, pero aplicados a promedio de bateo (xBA) y slugging (xSLG): Statcast calcula qué hits y bases totales produce, en promedio, un batazo con esa velocidad y ese ángulo.',
    scale: [['xBA .250', 'promedio'], ['xBA .300', 'muy bueno'], ['xSLG .410', 'promedio'], ['xSLG .500 o más', 'muy bueno'], ['xSLG .600 o más', 'élite']],
    use: 'Ver si el promedio y el poder de un jugador son reales o estuvieron inflados (o frenados) por la suerte.',
    worth: 'Es útil como diagnóstico, no como número final. Mejor mirar el xwOBA, que resume todo.',
    example: 'Yordan Álvarez tuvo .318 de xBA y .636 de xSLG en 2026.',
    related: ['xwoba', 'slg', 'avg'], aliases: ['xBA', 'xSLG'],
  },
  {
    id: 'ops', label: 'OPS', full: 'On-base Plus Slugging (embasarse más slugging)', category: 'bateo',
    short: 'La suma del OBP y el SLG: una forma rápida de medir cuánta ofensiva produce un bateador.',
    what: 'Se calcula sumando el porcentaje de embasarse (OBP) y el slugging (SLG). Combina "llegar a base" y "pegar con poder" en un solo número fácil de recordar.',
    scale: [['.700', 'promedio aproximado'], ['.800', 'bueno'], ['.900', 'muy bueno'], ['1.000 o más', 'élite']],
    use: 'Es el atajo más común para hablar de qué tan bueno es un bateador. Aparece en casi todos los reportes.',
    worth: 'Es fácil de entender, pero le da el mismo peso al OBP y al SLG cuando embasarse vale más que el poder. Tampoco ajusta por estadio ni incluye defensa. Por eso wOBA y wRC+ son más precisas.',
    example: 'Yordan Álvarez tuvo 1.033 de OPS en 2026.',
    related: ['obp', 'slg', 'wrcplus'], aliases: ['OPS'],
  },
  {
    id: 'obp', label: 'OBP', full: 'On-Base Percentage (porcentaje de embasarse)', category: 'bateo',
    short: 'De cada 100 turnos, cuántas veces el bateador llega a base por hit, boleto o golpe.',
    what: 'Es el porcentaje de veces que un bateador llega a base. Cuenta hits, boletos y pelotazos. No cuenta llegar por error ni por jugada de selección.',
    scale: [['.300', 'bajo'], ['.320', 'promedio'], ['.350', 'bueno'], ['.400 o más', 'élite']],
    use: 'Medir cuánto evita el bateador los outs, que es lo más valioso que puede hacer.',
    worth: 'Vale más que el promedio de bateo porque cuenta los boletos. No dice si llega con un sencillo o con un jonrón; para eso está el SLG.',
    example: 'Yordan Álvarez tuvo .432 de OBP en 2026.',
    related: ['ops', 'slg', 'avg'], aliases: ['OBP'],
  },
  {
    id: 'slg', label: 'SLG', full: 'Slugging (bases por turno al bate)', category: 'bateo',
    short: 'Cuántas bases consigue un bateador por cada turno al bate. Mide poder.',
    what: 'Se calcula dividiendo las bases totales entre los turnos al bate. Un sencillo vale 1, un doble 2, un triple 3 y un jonrón 4. Por eso mide el poder, no solo si pega hits.',
    scale: [['.400', 'promedio aproximado'], ['.450', 'bueno'], ['.500', 'muy bueno'], ['.600 o más', 'élite']],
    use: 'Distinguir al bateador de poder del que solo pega sencillos.',
    worth: 'No cuenta los boletos y trata las bases como si valieran igual de carreras (en realidad un jonrón vale más que cuatro sencillos de uno). Se usa dentro del OPS.',
    example: 'Pete Crow-Armstrong tuvo .570 de SLG en 2026.',
    related: ['ops', 'obp', 'avg'], aliases: ['SLG'],
  },
  {
    id: 'avg', label: 'AVG', full: 'Promedio de bateo (batting average)', category: 'bateo',
    short: 'De cada 10 turnos al bate, cuántas veces el bateador pega hit.',
    what: 'Son los hits divididos entre los turnos al bate (sin contar boletos). Un .300 significa que pega hit en 3 de cada 10 turnos.',
    scale: [['.230', 'bajo'], ['.245', 'promedio'], ['.280', 'bueno'], ['.300 o más', 'muy bueno']],
    use: 'Es la estadística clásica para hablar de contacto.',
    worth: 'Hoy pesa menos que el OBP o el SLG: ignora los boletos y trata igual un sencillo y un jonrón. Es el dato más fácil de entender, pero el menos completo.',
    example: 'Yordan Álvarez bateó .316 en 2026.',
    related: ['obp', 'slg', 'xstats'], aliases: ['AVG'],
  },
  {
    id: 'era', label: 'ERA', full: 'Earned Run Average (efectividad)', category: 'pitcheo',
    short: 'Carreras limpias que permite un lanzador por cada 9 entradas. Menos es mejor.',
    what: 'Es el promedio de carreras limpias (las que no vienen de errores) que concede un lanzador en nueve entradas. Una ERA de 2.00 significa que permite unas 2 carreras por juego completo.',
    scale: [['4.00', 'promedio aproximado'], ['3.50', 'bueno'], ['3.00', 'muy bueno'], ['2.50 o menos', 'élite']],
    use: 'Medir cuánto castigan a un lanzador, la forma más simple de verlo.',
    worth: 'Depende de la defensa que tenga detrás y de la suerte con los batazos. Por eso se mira junto con el FIP y el xERA, que quitan esas influencias.',
    example: 'Jacob Misiorowski terminó 2026 con 1.80 de ERA.',
    related: ['fip', 'xera', 'whip'], aliases: ['ERA'],
  },
  {
    id: 'whip', label: 'WHIP', full: 'Walks plus Hits per Inning Pitched (boletos más hits por entrada)', category: 'pitcheo',
    short: 'Cuántos corredores permite un lanzador por entrada, por hit o boleto. Menos es mejor.',
    what: 'Suma los boletos y los hits que concede un lanzador y los divide entre las entradas lanzadas. Un 1.00 significa un corredor por entrada.',
    scale: [['1.30', 'promedio aproximado'], ['1.20', 'bueno'], ['1.10', 'muy bueno'], ['1.00 o menos', 'élite']],
    use: 'Medir qué tanto mantiene limpias las bases.',
    worth: 'Útil y fácil de leer, pero trata igual un hit y un boleto, y no dice cuántos corredores anotaron.',
    example: 'Jacob Misiorowski terminó 2026 con 0.80 de WHIP.',
    related: ['era', 'fip'], aliases: ['WHIP'],
  },
  {
    id: 'fip', label: 'FIP', full: 'Fielding Independent Pitching (pitcheo independiente de la defensa)', category: 'pitcheo',
    short: 'Una "ERA justa": mide solo lo que el lanzador controla, que son ponches, boletos, golpeados y jonrones.',
    what: 'Calcula cuál habría sido la efectividad del lanzador si la defensa y la suerte con los batazos hubieran sido normales. Usa solo ponches, boletos, pelotazos y jonrones. Se muestra en la misma escala que la ERA.',
    scale: [['4.00', 'promedio aproximado'], ['3.50', 'bueno'], ['3.00', 'muy bueno'], ['2.50 o menos', 'élite']],
    use: 'Ver si la ERA de un lanzador es merecida. Una ERA mucho menor que su FIP sugiere suerte o muy buena defensa.',
    worth: 'Predice mejor el futuro que la ERA. No ve la calidad del contacto que permite, que sí mide el xERA. Es la base del fWAR de los lanzadores.',
    example: 'Cam Schlittler tuvo 1.95 de ERA y 2.56 de FIP en 2026.',
    related: ['era', 'xera', 'fwar'], aliases: ['FIP'],
  },
  {
    id: 'xera', label: 'xERA', full: 'ERA esperada (expected ERA)', category: 'statcast',
    short: 'La efectividad que debería tener un lanzador según la calidad del contacto que permite.',
    what: 'Statcast mide la velocidad y el ángulo de cada batazo que recibe el lanzador, más sus ponches y boletos, y calcula qué ERA le correspondería. Quita la suerte y la defensa.',
    scale: [['4.00', 'promedio aproximado'], ['3.00', 'muy bueno'], ['2.50 o menos', 'élite']],
    use: 'Comprobar si la ERA real engaña. Si la ERA es mucho menor que el xERA, es posible que suba.',
    worth: 'Buen diagnóstico con muestras grandes. No reemplaza a la ERA real, que sí cuenta las carreras que ocurrieron.',
    example: 'Cam Schlittler tuvo 2.85 de xERA en 2026, algo mayor que su ERA real de 1.95.',
    related: ['era', 'fip'], aliases: ['xERA'],
  },
  {
    id: 'kpct', label: 'K%', full: 'Porcentaje de ponches', category: 'bateo',
    short: 'De cada 100 apariciones, cuántas terminan en ponche. En bateadores es mejor que sea bajo; en lanzadores, alto.',
    what: 'Son los ponches divididos entre las apariciones al plato. Se ve desde los dos lados: el bateador quiere evitarlos y el lanzador quiere conseguirlos.',
    scale: [['Bateador: 15%', 'muy bueno (pocos ponches)'], ['22%', 'promedio aproximado'], ['30% o más', 'muchos ponches'], ['Lanzador: 28% o más', 'muy bueno']],
    use: 'Medir el contacto del bateador o la capacidad de dominar del lanzador.',
    worth: 'En lanzadores es una de las señales más fiables del talento. En bateadores es menos decisivo: hay grandes bateadores que se ponchan mucho si compensan con poder y boletos.',
    example: 'Cam Schlittler ponchó a 31.4% de los bateadores en 2026.',
    related: ['bbpct', 'whiff'], aliases: ['K %', 'K%'],
  },
  {
    id: 'bbpct', label: 'BB%', full: 'Porcentaje de boletos', category: 'bateo',
    short: 'De cada 100 apariciones, cuántas terminan en base por bolas.',
    what: 'Son los boletos divididos entre las apariciones al plato. Para el bateador, alto es bueno; para el lanzador, bajo es bueno.',
    scale: [['5%', 'pocos boletos'], ['8%', 'promedio aproximado'], ['11%', 'muy bueno'], ['14% o más', 'élite']],
    use: 'Medir la paciencia y el control de la zona.',
    worth: 'Los boletos son parte del OBP y se asocian con buen ojo. Un bateador con mucho boleto produce aunque no pegue hits.',
    example: 'Yordan Álvarez tuvo 15.8% de BB en 2026.',
    related: ['kpct', 'obp', 'chase'], aliases: ['BB %', 'BB%'],
  },
  {
    id: 'wpa', label: 'WPA', full: 'Win Probability Added (probabilidad de victoria añadida)', category: 'contexto',
    short: 'Cuánto cambió un jugador, jugada tras jugada, la probabilidad de que su equipo ganara.',
    what: 'En cada turno la probabilidad de ganar del equipo sube o baja. Un jonrón en el 9.º inning con el juego empatado la sube mucho; el mismo jonrón en una paliza casi no cambia nada. El WPA suma todo eso durante la temporada, expresado en victorias.',
    scale: [['0', 'promedio'], ['+2', 'muy bueno'], ['+4', 'estrella'], ['+5 o más', 'élite']],
    use: 'Contar la historia de quién rindió en los momentos que más pesaron. Se usa mucho en debates de MVP.',
    worth: 'Premia el contexto, pero el contexto no lo controla el jugador: pegar con corredores en base depende de la alineación. Sirve para describir lo que pasó, no para predecir.',
    example: 'Yordan Álvarez sumó 6.9 de WPA en 2026, el más alto de los candidatos.',
    related: ['re24', 'war'], aliases: ['WPA'],
  },
  {
    id: 're24', label: 'RE24', full: 'Carreras sobre lo esperado según estado de bases y outs', category: 'contexto',
    short: 'Cuántas carreras aportó un jugador más de lo esperado, según las bases ocupadas y los outs de cada turno.',
    what: 'Existen 24 combinaciones posibles de corredores y outs, y cada una vale una cantidad esperada de carreras. El RE24 mide cuánto cambia el jugador ese valor con cada turno. Es parecido al WPA, pero en carreras en vez de victorias y sin importar el marcador.',
    scale: [['0', 'promedio'], ['+30', 'muy bueno'], ['+50 o más', 'élite']],
    use: 'Medir producción con corredores en base de forma justa.',
    worth: 'Depende de la suerte de tener compañeros que lleguen a base. Es una buena descripción de lo ocurrido, no una medida pura del talento.',
    example: 'Yordan Álvarez tuvo cerca de 76 de RE24 en 2026.',
    related: ['wpa'], aliases: ['RE24'],
  },
  {
    id: 'barrel', label: 'Barrel', full: 'Batazo perfecto (barrel)', category: 'statcast',
    short: 'Un batazo con la combinación ideal de velocidad y ángulo, la que casi siempre es hit de extra bases.',
    what: 'Statcast define un barrel como un batazo cuya velocidad y ángulo producen históricamente un promedio de al menos .500 y un slugging de al menos 1.500. El "Barrel %" es el porcentaje de batazos en juego que cumplen eso.',
    scale: [['5%', 'bajo'], ['8%', 'promedio aproximado'], ['12%', 'muy bueno'], ['15% o más', 'élite']],
    use: 'Identificar al bateador que pega con poder de verdad y no solo hits sueltos.',
    worth: 'Es uno de los mejores indicadores del poder real. Un barrel no es lo mismo que un jonrón: depende del estadio y de la defensa.',
    example: 'Yordan Álvarez tuvo 16.0% de Barrel en 2026.',
    related: ['ev', 'hardhit', 'la'], aliases: ['Barrel %', 'barrels', 'Barrel', 'barrel'],
  },
  {
    id: 'hardhit', label: 'Hard-Hit %', full: 'Porcentaje de batazos fuertes', category: 'statcast',
    short: 'El porcentaje de batazos que salen del bate a 95 mph o más.',
    what: 'Cuenta los batazos en juego con una velocidad de salida de 95 mph o más, divididos entre todos los batazos en juego.',
    scale: [['35%', 'bajo'], ['39%', 'promedio aproximado'], ['45%', 'muy bueno'], ['50% o más', 'élite']],
    use: 'Medir quién pega más fuerte, sin importar el ángulo.',
    worth: 'Fuerte no siempre es bueno: un batazo a 100 mph hacia el piso es un rolling. Por eso se mira junto con el ángulo (barrel).',
    example: 'Yordan Álvarez tuvo 53.8% de Hard-Hit en 2026.',
    related: ['ev', 'barrel'], aliases: ['Hard-Hit %', 'Hard-Hit'],
  },
  {
    id: 'ev', label: 'Velocidad de salida', full: 'Exit velocity (velocidad de la pelota al salir del bate)', category: 'statcast',
    short: 'Qué tan rápido sale la pelota del bate, en millas por hora.',
    what: 'Statcast la mide en cada batazo con radar. Se usa el promedio de toda la temporada y la máxima, que muestra el techo de poder del bateador.',
    scale: [['85 mph', 'bajo'], ['88 mph', 'promedio aproximado'], ['92 mph o más', 'muy bueno'], ['Máxima de 115 mph o más', 'poder élite']],
    use: 'Medir la fuerza bruta del contacto.',
    worth: 'Es tan solo una parte: sin buen ángulo, la pelota fuerte puede ser un rolling. Con el ángulo da el barrel.',
    example: 'Yordan Álvarez promedió 94.4 mph en 2026 y tuvo un batazo de 118.5 mph.',
    related: ['la', 'barrel', 'hardhit'], aliases: ['Vel. de salida', 'velocidad de salida', 'Velocidad de salida'],
  },
  {
    id: 'la', label: 'Ángulo de lanzamiento', full: 'Launch angle (ángulo de salida de la pelota)', category: 'statcast',
    short: 'El ángulo vertical con el que sale la pelota del bate, en grados.',
    what: 'Cero grados es una línea horizontal. Por encima de 0 es elevado y por debajo es un rolling. Los ángulos entre 8 y 32 grados se llaman "sweet spot" y producen la mayoría de los hits de calidad.',
    scale: [['Menos de 8°', 'rolling'], ['8° a 32°', 'sweet spot'], ['25° a 30°', 'zona típica de jonrón'], ['Más de 40°', 'pelota alta fácil de atrapar']],
    use: 'Entender qué tipo de batazos produce un bateador.',
    worth: 'No hay un ángulo ideal para todos: depende de la velocidad. Un batazo a 105 mph rinde con más ángulos que uno a 85.',
    example: 'El ángulo promedio de Yordan Álvarez en 2026 fue de 19.1 grados.',
    related: ['ev', 'barrel', 'sweetspot'], aliases: ['Ángulo de lanzamiento', 'ángulo de lanzamiento'],
  },
  {
    id: 'sweetspot', label: 'Sweet spot %', full: 'Porcentaje de batazos en el ángulo ideal', category: 'statcast',
    short: 'El porcentaje de batazos que salen con un ángulo entre 8 y 32 grados.',
    what: 'Mide cuántas veces el bateador pega la pelota en el rango de ángulos que más hits produce.',
    scale: [['30%', 'bajo'], ['33%', 'promedio aproximado'], ['40% o más', 'muy bueno']],
    use: 'Medir la consistencia del buen contacto.',
    worth: 'Ayuda a explicar por qué algunos bateadores tienen promedios altos de forma sostenida.',
    example: 'Yordan Álvarez tuvo 40% de Sweet Spot en 2026 según Savant.',
    related: ['la', 'barrel'], aliases: ['Sweet spot %'],
  },
  {
    id: 'whiff', label: 'Whiff %', full: 'Porcentaje de fallos al hacer swing', category: 'statcast',
    short: 'De los swings que hace un bateador, cuántos falla por completo.',
    what: 'Es el porcentaje de swings que no hacen ningún contacto con la pelota. Para el bateador, menos es mejor. Para el lanzador, más es mejor.',
    scale: [['Bateador: 18%', 'muy bueno'], ['25%', 'promedio aproximado'], ['32% o más', 'muchos fallos']],
    use: 'Medir contacto (bateador) o poder de engaño (lanzador).',
    worth: 'En lanzadores es una de las señales más claras del talento. En bateadores, mirar junto con el poder.',
    example: 'Jacob Misiorowski logró 37.3% de whiffs en 2026.',
    related: ['chase', 'kpct', 'csw'], aliases: ['Whiff %', 'whiffs', 'whiff'],
  },
  {
    id: 'chase', label: 'Chase %', full: 'Porcentaje de swings a lanzamientos fuera de la zona', category: 'statcast',
    short: 'Cuántas veces el bateador hace swing a un lanzamiento que no era strike.',
    what: 'Mide la disciplina: de los lanzamientos fuera de la zona de strike, en cuántos hace swing el bateador.',
    scale: [['20%', 'muy disciplinado'], ['28%', 'promedio aproximado'], ['35% o más', 'muy agresivo']],
    use: 'Medir el ojo para la zona.',
    worth: 'Un bateador con poca persecución recibe más buenos lanzamientos y más boletos. No siempre es malo perseguir si el bateador conecta.',
    example: 'Kevin McGonigle persiguió solo 19.6% de los lanzamientos fuera de la zona en 2026.',
    related: ['whiff', 'bbpct'], aliases: ['Chase %'],
  },
  {
    id: 'bsr', label: 'Corrido de bases (BsR)', full: 'Base Running (carreras por corrido de bases)', category: 'campo',
    short: 'Cuántas carreras suma o resta un jugador con su corrido: robos, avances extra y evitar outs.',
    what: 'Mide las carreras que un jugador aporta (o quita) sobre el promedio por todo lo que hace corriendo las bases: robos, avanzar una base más de lo normal, no ser out en un robo ni en jugadas de apuro.',
    scale: [['-5', 'malo'], ['0', 'promedio'], ['+5', 'bueno'], ['+10 o más', 'élite']],
    use: 'Completar el cuadro de valor del jugador más allá del bate.',
    worth: 'Solo cuenta hasta unas 10 carreras al año (1 victoria) en los casos extremos. Importa más en jugadores veloces.',
    example: 'Bobby Witt Jr. sumó 9.3 carreras corriendo las bases en 2026.',
    related: ['war', 'sprint'], aliases: ['BsR'],
  },
  {
    id: 'fld', label: 'Defensa (carreras)', full: 'Carreras salvadas por la defensa', category: 'campo',
    short: 'Cuántas carreras salva un jugador con el guante respecto a un defensor promedio de su posición.',
    what: 'Es la medida de defensa que usa el WAR. Compara qué tantas jugadas convierte el jugador contra lo que haría un defensor promedio en su posición. Los sitios usan sistemas distintos (OAA, DRS, UZR).',
    scale: [['-10', 'malo'], ['0', 'promedio'], ['+10', 'muy bueno'], ['+15 o más', 'élite']],
    use: 'Medir el valor del guante, que es una parte importante del WAR de campocortos y jardineros centrales.',
    worth: 'Es la parte menos fiable del WAR: una sola temporada de defensa tiene mucho ruido. Por eso los WAR de dos sitios pueden diferir más en defensores.',
    example: 'Pete Crow-Armstrong sumó 21.1 carreras con su defensa en 2026.',
    related: ['oaa', 'posadj', 'war'], aliases: ['Defensa de', 'defensa (carreras)'],
  },
  {
    id: 'posadj', label: 'Ajuste por posición', full: 'Positional adjustment', category: 'campo',
    short: 'Un ajuste del WAR que premia las posiciones difíciles de defender y resta a las fáciles.',
    what: 'No todas las posiciones valen igual. Es más difícil encontrar un cátcher o un campocorto que defiendan bien que un primera base. Por eso el WAR suma carreras a posiciones difíciles y resta a las fáciles. FanGraphs, por ejemplo, suma unas 12 carreras por temporada a un cátcher y resta unas 17 a un designado.',
    scale: [['Cátcher y campocorto', 'suman'], ['Segunda, tercera y jardín central', 'suman poco'], ['Jardín corto y primera base', 'restan'], ['Designado', 'resta más']],
    use: 'Comparar con justicia a un jugador de posición difícil con uno de posición fácil.',
    worth: 'Por eso un bateador designado necesita un bate extraordinario para acumular WAR. Es una de las razones por las que el WAR de Yordan Álvarez es menor que lo que dice su bate.',
    example: 'Yordan Álvarez fue designado casi todo el año y tiene un ajuste negativo en su WAR.',
    related: ['war', 'fld'], aliases: ['ajuste por posición'],
  },
  {
    id: 'oaa', label: 'OAA', full: 'Outs Above Average (outs sobre el promedio)', category: 'campo',
    short: 'Cuántos outs más (o menos) convierte un defensor que el promedio, según Statcast.',
    what: 'Statcast mide la dificultad de cada jugada (distancia a recorrer, dirección y tiempo disponible) y calcula cuántos outs más o menos convierte el defensor comparado con el promedio.',
    scale: [['-5', 'malo'], ['0', 'promedio'], ['+5', 'muy bueno'], ['+10 o más', 'élite']],
    use: 'Medir la defensa con datos objetivos, no con juicios de scouts.',
    worth: 'Es una de las mejores medidas de defensa, pero cuenta jugadas de un solo año. Mejor usarla con varios años.',
    example: 'Bobby Witt Jr. tuvo 22 OAA a fines de septiembre, el mejor de la Liga Americana según MLB.com.',
    related: ['fld', 'war'], aliases: ['OAA', 'Outs sobre el prom.'],
  },
  {
    id: 'sprint', label: 'Velocidad de carrera', full: 'Sprint speed', category: 'campo',
    short: 'Qué tan rápido corre un jugador en su mejor sprint, en pies por segundo.',
    what: 'Statcast mide la velocidad en pies por segundo en la parte más rápida de sus carreras (las que hace con esfuerzo máximo).',
    scale: [['25 ft/s', 'lento'], ['27 ft/s', 'promedio'], ['28.5 ft/s', 'rápido'], ['30 ft/s o más', 'élite']],
    use: 'Predecir robos, hits de infield y la defensa en jardines.',
    worth: 'Es capacidad, no resultado: un jugador muy rápido puede ser mal corredor, y uno lento puede ser inteligente.',
    example: 'Bobby Witt Jr. corrió a 30.1 ft/s en 2026.',
    related: ['bsr'], aliases: ['Velocidad de carrera', 'Vel. de carrera'],
  },
  {
    id: 'batspeed', label: 'Bat tracking', full: 'Medición del swing (velocidad del bate)', category: 'statcast',
    short: 'Statcast mide qué tan rápido se mueve la cabeza del bate y la longitud y el ángulo de ataque del swing.',
    what: 'Con cámaras de alta velocidad mide la velocidad de la cabeza del bate cuando golpea la pelota (en mph), cuánto recorre en el swing y el ángulo con el que ataca. Un "swing rápido" es el que supera las 75 mph.',
    scale: [['68 mph', 'lento'], ['72 mph', 'promedio aproximado'], ['75 mph o más', 'swing rápido'], ['78 mph', 'élite']],
    use: 'Explicar de dónde viene el poder de un bateador y qué tan rápido es su swing.',
    worth: 'Un bate rápido da más potencial de poder, pero no garantiza buen contacto. Es un dato nuevo de Statcast con pocos años de historia.',
    example: 'Yordan Álvarez promedió 74.9 mph de velocidad de bate en 2026.',
    related: ['ev', 'barrel'], aliases: ['Bat tracking', 'bat tracking', 'Vel. del bate', 'Velocidad de bate', 'velocidad de bate'],
  },
  {
    id: 'csw', label: 'CSW %', full: 'Called Strikes plus Whiffs (strikes cantados más swings fallados)', category: 'pitcheo',
    short: 'Qué porcentaje de los lanzamientos de un pitcher terminan en strike cantado o swing fallado.',
    what: 'Suma los strikes cantados y los swings fallados y los divide entre todos los lanzamientos. Es una medida rápida de qué tan bien "gana" el lanzador cada pitcheo.',
    scale: [['25%', 'bajo'], ['28%', 'promedio aproximado'], ['30% o más', 'muy bueno']],
    use: 'Evaluar un lanzamiento (o un lanzador) más allá de lo que pasa en los resultados.',
    worth: 'Es un buen indicador de lo que el lanzador controla y se estabiliza rápido con pocas salidas.',
    example: 'La recta de Cam Schlittler logró 33% de CSW en 2026.',
    related: ['whiff', 'kpct'], aliases: ['CSW %', 'CSW'],
  },
  {
    id: 'putaway', label: 'Putaway %', full: 'Porcentaje de cierre (ponches con dos strikes)', category: 'pitcheo',
    short: 'Cuántas veces un lanzamiento con dos strikes termina en ponche.',
    what: 'De todos los lanzamientos que un pitcher lanza con dos strikes, el porcentaje que termina en ponche.',
    scale: [['Más alto es mejor', 'indica cuánto "cierra" el lanzamiento']],
    use: 'Saber cuál lanzamiento es el mejor para sacar el último out del turno.',
    worth: 'Útil para comparar los lanzamientos de un mismo lanzador entre sí.',
    example: 'La recta de Cam Schlittler tuvo 27% de putaway en 2026.',
    related: ['csw', 'whiff'], aliases: ['Putaway %'],
  },
  {
    id: 'percentil', label: 'Percentil', full: 'Percentil de Baseball Savant', category: 'statcast',
    short: 'Un ranking de 0 a 100: indica cuántos jugadores de MLB quedan por debajo del suyo en esa métrica.',
    what: 'Un percentil 90 significa que el jugador es mejor que el 90% de la liga en esa métrica. El 50 es el promedio. En las barras de Savant, el rojo es élite y el azul es bajo. Savant ya invierte las métricas en las que menos es mejor (ponches de bateador, persecución), así que en todas, rojo es bueno.',
    scale: [['0 a 25', 'bajo'], ['50', 'promedio'], ['75 a 89', 'muy bueno'], ['90 a 100', 'élite']],
    use: 'Ver de un vistazo en qué es élite un jugador y en qué no.',
    worth: 'Muestra posición relativa, no el valor absoluto. Un percentil 99 en una métrica poco importante no hace a un jugador excelente.',
    example: 'Yordan Álvarez está en el percentil 100 de xwOBA, xBA y xSLG en 2026.',
    related: ['statcast'], aliases: ['percentiles', 'percentil', 'Percentil'],
  },
  {
    id: 'statcast', label: 'Statcast', full: 'Sistema de rastreo de MLB', category: 'statcast',
    short: 'El sistema de cámaras y radar de MLB que mide cada lanzamiento, batazo y jugada en todos los estadios.',
    what: 'Está instalado en todos los parques desde 2015. Mide velocidad, ángulo, giro y movimiento de los lanzamientos, y velocidad, ángulo y trayectoria de los batazos, además de la ubicación y la velocidad de los jugadores. Baseball Savant es la página pública donde se ven esos datos.',
    use: 'Es de donde sale casi todo el análisis moderno: barrel, xwOBA, OAA, velocidad de carrera y bat tracking.',
    worth: 'Cambió la forma de evaluar al jugador, porque pasó de medir resultados a medir cómo se producen. Sigue siendo una herramienta de MLB y no cuenta cosas como el liderazgo o el contexto.',
    related: ['xwoba', 'barrel', 'oaa'], aliases: ['Statcast'],
  },
]

export const GLOSSARY: Record<string, Entry> = Object.fromEntries(E.map((e) => [e.id, e]))
export const ENTRIES = E

/** Aliases ordenados de mayor a menor largo para que "fWAR" gane a "WAR", etc. */
const ALIAS_LIST: { alias: string; id: string }[] = E.flatMap((e) => e.aliases.map((a) => ({ alias: a, id: e.id }))).sort((a, b) => b.alias.length - a.alias.length)

const esc = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')

export const ALIAS_RE = new RegExp(`(?<![\\wÁ-ú])(${ALIAS_LIST.map((a) => esc(a.alias)).join('|')})(?![\\wÁ-ú])`, 'g')

export const aliasToId = (alias: string) => ALIAS_LIST.find((a) => a.alias === alias)?.id
